apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: platform-secret-store
spec:
  provider:
    kubernetes:
      remoteNamespace: vault
      auth:
        serviceAccount:
          name: external-secrets
          namespace: external-secrets
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
          namespace: external-secrets
