apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
  namespace: demo
data:
  index.html: |
    <!doctype html>
    <html>
      <head>
        <meta charset="utf-8"/>
        <title>demo-nginx-dev</title>
      </head>
      <body style="font-family: Arial, sans-serif;">
        <h1>GitOps works âœ…</h1>
        <p>app: demo-nginx-dev</p>
        <p>version: v1</p>
      </body>
    </html>
