resources:
  - ../../base
nameSuffix: -dev
patches:
  - target:
      kind: Ingress
      name: nginx
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: demo-nginx-dev.lab.local
  - target:
      kind: Rollout
      name: nginx
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
      - op: replace
        path: /spec/strategy/canary/stableService
        value: nginx-dev
      - op: replace
        path: /spec/strategy/canary/canaryService
        value: nginx-canary-dev
      - op: replace
        path: /spec/strategy/canary/trafficRouting/nginx/stableIngress
        value: nginx-dev
