resources:
  - ../../base
nameSuffix: -dev
patches:
  - target:
      kind: Ingress
      name: nginx
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: demo-nginx-dev.lab.local
  - target:
      kind: Rollout
      name: nginx
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - path: rollout-patch.yaml
  - path: image-patch.yaml
