resources:
  - rollouts.yaml
  - loki.yaml
  - promtail.yaml
  - ingress-nginx.yaml
  - metallb.yaml
  - config/metallb-config.yaml
  - monitoring.yaml
  - cert-manager.yaml
  - config/cert-manager-issuer.yaml
